### ISSUE TITLE
All the files should be owned by us or a member of sisimai project

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/set-of-emails#6]
https://github.com/sisimai/p5-Sisimai/issues/274#issuecomment-378504475
```
I've another problem for Debian packaging: the directory set-of-emails/ has no clear copyright
(one mail mention a sort of copyright from Amazon but without any license. Do you have more
information? For now, I've removed this directory and disabled related tests
(see https://salsa.debian.org/perl-team/modules/packages/libsisimai-perl)

```

**Comment by guimard** [comment]
`set-of-emails/maildir/bsd/email-amazonses-04.eml`: "Copyright 2010 Amazon.com, Inc. or its affiliates. All Rights Reserved."

**Comment by guimard** [comment]
(@azumakuniyuki : your cat is quiter than mine :smile:)

**Comment by guimard** [comment]
Sisimai has been pushed in https://ftp-master.debian.org/new.html the Debian NEW queue. Name libsisimai-perl, version 4.22.5+dfsg-1 _(`dfsg` means repackaged)_.
Since `set-of-emails` is used only for tests, package is fully usable.

**Comment by azumakuniyuki** [comment]
@guimard Perhaps, `Copyright 2010 Amazon.com. inc...` does not mean a copyright for the entire email including headers. However, I can not say explicitly that it is so. Then we'll remove the file from each repository until the next release.

And then, we will ask our lawyer that whether a bounce mail is a copyrighted work or not because all the  file are owned by us but some emails are given from sisimai's user (we've replaced email addresses, hostnames, and IP addresses with anonymized values).

By the way, the cat is a stray cat living in a fishing port and has passed away last winter at the age of 10 or 11 or 12.

Thanks :-)

**Comment by azumakuniyuki** [comment]
- Removed `email-amazonses-04.eml` from the following repositories:
  - set-of-emails
  - p5-Sisimai
  - rb-Sisimai
- Other uncertain copyright emails (if exists) might be removed
- We will get the answer from our lawyer at the next week

**Comment by azumakuniyuki** [comment]
The following sample emails will be removed
- [x] arf-03.eml
- [x] arf-04.eml
- [x] arf-05.eml
- [x] arf-06.eml
- [x] arf-07.eml
- [x] arf-08.eml
- [x] arf-09.eml
- [x] arf-10.eml
- [x] arf-13.eml
- [x] email-amazonworkmail-06.eml
- [x] email-bigfoot-01.eml
- [x] email-einsundeins-01.eml
- [x] email-exchange2003-06.eml
- [x] email-ezweb-06.eml
- [x] email-facebook-01.eml
- [x] email-facebook-02.eml
- [x] email-fml-01.eml
- [x] email-google-02.eml
- [x] email-google-14.eml
- [x] email-mailmarshalsmtp-01.eml
- [x] email-messagelabs-01.eml
- [x] email-outlook-05.eml
- [x] email-postfix-12.eml
- [x] email-postfix-21.eml
- [x] email-x3-04.eml
- [x] email-x4-07.eml
- [x] rfc3464-02.eml
- [x] rfc3464-03.eml
- [x] rfc3464-22.eml
- [x] rfc3464-23.eml
- [x] rfc3464-25.eml
- [x] rfc3464-27.eml
- [x] rhost-godaddy-01.eml

**Comment by azumakuniyuki** [comment]
@guimard All the files in the repository have been checked, and some files with unclear license have been removed. The latest `set-of-emails` are included in `p5-Sisimai` with `v4.22.5p1` tag at https://github.com/sisimai/p5-Sisimai/releases/tag/v4.22.5p1 .

Best regards.

**Comment by guimard** [comment]
@azumakuniyuki: thanks, I'll put this version to Debian

**Comment by guimard** [comment]
Note that Sisimai is now in Debian : https://tracker.debian.org/pkg/libsisimai-perl

**Comment by guimard** [comment]
What is your policy, do you publish intermediate versions on CPAN ?

**Comment by azumakuniyuki** [comment]
@guimard The next version of Sisimai, v4.22.6 will be released (publish to CPAN) at May or June when the patch level became 2 or 3.

**Comment by guimard** [comment]
@azumakuniyuki: thanks, this will be published in Debian then

**Comment by azumakuniyuki** [comment]
@guimard Hello, We've uploaded v4.22.6 on CPAN today :-) https://metacpan.org/release/Sisimai

**Comment by guimard** [comment]
@azumakuniyuki Thanks ! I've pushed it to salsa for Team review : https://salsa.debian.org/perl-team/modules/packages/libsisimai-perl

**Comment by guimard** [comment]
@azumakuniyuki: accepted in Debian/unstable !

**Comment by guimard** [comment]
Will migrate to Debian/testing and so to Ubuntu in 5-6 days

**Comment by azumakuniyuki** [comment]
@guimard Thank you so much !

**Comment by guimard** [comment]
You're welcome
