### ISSUE TITLE
Set-of-emails logo :)

### ISSUE THREAD

**Issue by batarian71** [sisimai/set-of-emails#8]
Hi, I created a new logo for you. If you like it, I will send you a file. I can design new logo in line with your requests.
![e4c8c99e-7c12-4f8a-8f14-cc45dc019e15](https://user-images.githubusercontent.com/36008612/39432040-2d00070e-4c9b-11e8-9810-484a235bfba8.jpg)

**Comment by azumakuniyuki** [comment]
Thanks for cool logos !!!
Orange logo is my favorite and I'll use the log at this repository :-)

**Comment by batarian71** [comment]
I sent pr @azumakuniyuki . I hope you like.

**Comment by azumakuniyuki** [comment]
Can I use the logo at https://github.com/sisimai/p5-Sisimai/tree/master/set-of-emails and https://github.com/sisimai/rb-Sisimai/tree/master/set-of-emails ? This repository is the master of these "set-of-emails".

**Comment by reallinfo** [comment]
Yeah, I can send a PR to the master repo. ?

**Comment by azumakuniyuki** [comment]
@batarian71 Both Pull-Requests successfully merged :-) Thanks !

**Comment by azumakuniyuki** [comment]
@batarian71 Hello,
We have a question about the logo file you created.
Does the logo file we've received include the copyright of the file ? In short, The copyright of the logo file is belong to us, is it correct ?

If the copyright of the file is owned by you, we will remove the logo and related files from repositories.

Best regards.

**Comment by batarian71** [comment]
you own the copyright of this logo. I just use the ccby license. 
https://creativecommons.org/licenses/by/4.0/

So You can use this logo. There is no problem.  Is it okay?

**Comment by azumakuniyuki** [comment]
@batarian71 Thanks :-) I'll write "CC BY 4.0" at README files later.

**Comment by batarian71** [comment]
you're welcome, okay :)
